### ISSUE TITLE
Connection to the Arduino

### ISSUE THREAD

**Issue by yani66** [DirkHeinke/arduinoToESPHome-guide#1]
I followed your tutorial and got the Esp running. I can see it in the ESPHome Overview, but I couldn't figure out how I should connect the Esp to the Arduino.
Would be nice if someone could help me with this.
yani66

(Esp: Esp-01, ESPHome-Version: 2022.11.2, Home Assistant-Version: Frontend 20221108.0 - latest)

**Comment by DirkHeinke** [comment]
Hi, nice you figured everything out. Is there anything I can improve on the tutorial to make things better?
